---
- name: ELK provision
  hosts: elk
  become: true
  gather_facts: false
  roles:
    - elastic_repo
    - elasticsearch
    - kibana

- name: Common provision
  hosts: all
  become: true
  gather_facts: false
  roles:
    - rsyslog
    - auditd

- name: Web provision
  hosts: web
  become: true
  gather_facts: false
  roles:
    - nginx
